### ISSUE TITLE
Figma To-do

### ISSUE THREAD

**Issue by Tmcc211** [Hacktzke/SPACE_JJAMT#25]
- [x] user profiles need work
- [x] add chat messages to comms frames
- [x] application frame needs set up and dev (source or choose contractors)
